name: flutter_mobile_template
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # icons
  cupertino_icons: ^1.0.4
  flutter_phosphor_icons: ^0.0.1+5
  font_awesome_flutter: ^10.3.0

  # core
  connectivity: ^3.0.6
  permission_handler: ^10.2.0

  # ui
  responsive_framework: ^0.2.0
  form_field_validator: ^1.1.0
  loading_overlay: ^0.3.0

  # state management
  get: ^4.6.1

  # files, images & player
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+4
  flutter_svg: ^1.0.0
  lottie: ^2.2.0
  youtube_player_flutter: ^8.0.0

  # code generator
  freezed_annotation: ^2.2.0

  # database
  get_storage: ^2.0.3

  # social auth
  flutter_facebook_auth: ^5.0.7
  google_sign_in: ^5.2.1

  # notifications
  onesignal_flutter: ^3.2.7

  # admob
  google_mobile_ads: ^2.3.0

  # others
  webview_flutter: ^4.0.2
  url_launcher: ^6.0.17
  device_info: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable:
  flutter_launcher_icons: ^0.11.0
  build_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  # === Generate Launcher Icon ===
  #flutter pub get
  #flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
